version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-serenamente_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-serenamente_password}
      POSTGRES_DB: ${POSTGRES_DB:-serenamente_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-serenamente_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: